#!/bin/bash

# Set paths
GENOME_DIR=/ibiscostorage/fmigliaccio/fmontemagno/mags_analysis/all_mags
OUTPUT_DIR=/ibiscostorage/fmigliaccio/fmontemagno/mags_analysis/output/gtdktk
DB_PATH=/ibiscostorage/GiovannelliLab/db/geomosaic_extdb/mags_gtdbtk_extdb
MASH_DB=${DB_PATH}/mash_db_gtdbtk.msh
DATA_PATH=${DB_PATH}/release220

# Run GTDB-Tk
GTDBTK_DATA_PATH=/ibiscostorage/GiovannelliLab/db/geomosaic_extdb/mags_gtdbtk_extdb/release220 gtdbtk classify_wf \
  --genome_dir /ibiscostorage/fmigliaccio/fmontemagno/mags_analysis/all_mags \
  --out_dir /ibiscostorage/fmigliaccio/fmontemagno/mags_analysis/output/gtdktk \
  --cpus 12 \
  --extension fa
